apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-example
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: sidecar-example
    spec:
      containers:
      # Logger app
      - name: logger
        image: ${TEST_LOGGER_IMAGE}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        env:
        - name: LOG_DIR
          value: /var/log
        - name: LOG_INTERVAL
          value: "1"
      # fluentd sidecar
      - name: sidecar
        image: ${FLUENTD_SIDECAR_IMAGE}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: AGGREGATOR_AGENT_URL
          value: http://$(NODE_NAME):8888
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: config-volume
          mountPath: /etc/fluent/config.d
      volumes:
      - name: varlog
        emptyDir: {}
      - name: config-volume
        configMap:
          defaultMode: 420
          name: fluentd-config
